id: P979F5AF2
initial_creation_type: input
source_metadata:
  title: Works of Ngagchang Kunga Rinchen (vol. 2)
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    0ac0:
      title: མོལ་གཏམ་ཡིད་བཞིན་ནོར་བུ།
      author: སྔགས་འཆང་ཀུན་དགའ་རིན་ཆེན།
      base_file: 0ac0.txt
      order: 1
    1e98:
      title: བདག་ཆེན་ཀུན་ལེགས་པ་ལ་གནང་བའི་བཀའ་ཤོག སྔགས་འཆང་བཀའ་འབུམ་པོ་ཏི་གཉིས་པ་འདི།
        །ངག་དབང་ཀུན་བསོད་དད་དང་བརྩོན་པས་བསྡེབས། །བསོད་ནམས་འདི་ཡིས་བདག་ཅག་དཔོན་སློབ་ཀྱི།
        །འདི་ཕྱིའི་དོན་ཀུན་ཡིད་བཞིན་འགྲུབ་གྱུར་ཅིག།
      author: སྔགས་འཆང་ཀུན་དགའ་རིན་ཆེན།
      base_file: 1e98.txt
      order: 2
created_at: '2022-04-06T16:30:17.254306'
last_modified_at: '2022-04-06T16:30:17.254314'
